# Generated by Django 4.2.6 on 2023-11-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('curse', models.CharField(max_length=255)),
                ('music_instrument', models.CharField(choices=[('piano', 'Фортепиано'), ('guitar', 'Гитара'), ('violin', 'Скрипка')], max_length=255)),
                ('grade', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=255)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
